databases:
  - name: pcsl
    databaseName: pcsl
    user: pcsl
    plan: free

services:
  - type: web
    name: pcsl
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pcsl
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false