databases:
  - name: pcsl-backend
    databaseName: pcsl-backend
    user: pcsl-backend
    plan: free

services:
  - type: web
    name: pcsl-backend
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pcsl-backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false